baseURL: http://example.org/
languageCode: en-us
title: Some Cool Site
sectionPagesMenu: "main"

outputs:
  home: ["HTML", "JSON"]
  section: ["HTML", "RSS", "JSON"]
  page: ["HTML", "JSON"]
  taxonomy: ["RSS"]
